version: '3'

services:
  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:root@host.docker.internal:3306/cso_database  # Use host.docker.internal to connect to local MySQL
